#ifndef RFIDREADERDLL_GLOBAL_H
#define RFIDREADERDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RFIDREADERDLL_LIBRARY)
#define RFIDREADERDLL_EXPORT Q_DECL_EXPORT
#else
#define RFIDREADERDLL_EXPORT Q_DECL_IMPORT
#endif

#endif // RFIDREADERDLL_GLOBAL_H
